/* eslint-disable sort-keys */

import { DeclarationPrefixMap, PrefixMap } from './types';

export const declarationMapping: DeclarationPrefixMap = {
  'background-clip': { prefixes: 1 },
  appearance: { prefixes: 3 },
  'backdrop-filter': { prefixes: 1 },
  'box-decoration-break': { prefixes: 1 },
  'clip-path': { prefixes: 1 },
  'color-adjust': { prefixes: 1 },
  background: { functions: { 'cross-fade': 1, element: 2, 'image-set': 1 } },
  'background-image': { functions: { 'cross-fade': 1, element: 2, 'image-set': 1 } },
  'border-image': { functions: { 'cross-fade': 1, element: 2, 'image-set': 1 } },
  mask: { functions: { 'cross-fade': 1, element: 2, 'image-set': 1 }, prefixes: 1 },
  'list-style': { functions: { 'cross-fade': 1, element: 2, 'image-set': 1 } },
  'list-style-image': { functions: { 'cross-fade': 1, element: 2, 'image-set': 1 } },
  content: { functions: { 'cross-fade': 1, element: 2, 'image-set': 1 } },
  'mask-image': { functions: { 'cross-fade': 1, element: 2, 'image-set': 1 }, prefixes: 1 },
  hyphens: { prefixes: 5 },
  cursor: { functions: { 'image-set': 1 } },
  'mask-border-outset': { prefixes: 1 },
  'mask-border-repeat': { prefixes: 1 },
  'mask-border-slice': { prefixes: 1 },
  'mask-border-source': { prefixes: 1 },
  'mask-border-width': { prefixes: 1 },
  'mask-border': { prefixes: 1 },
  'mask-clip': { prefixes: 1 },
  'mask-composite': { prefixes: 1 },
  'mask-origin': { prefixes: 1 },
  'mask-position': { prefixes: 1 },
  'mask-repeat': { prefixes: 1 },
  'mask-size': { prefixes: 1 },
  'text-orientation': { prefixes: 1 },
  'unicode-bidi': { values: { isolate: 1, 'isolate-override': 1, plaintext: 1 } },
  'tab-size': { prefixes: 2 },
  'font-kerning': { prefixes: 1 },
  width: { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
  'min-width': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
  'max-width': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
  height: { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
  'min-height': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
  'max-height': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
  'inline-size': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
  'min-inline-size': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
  'max-inline-size': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
  'block-size': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
  'min-block-size': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
  'max-block-size': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
  grid: { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
  'grid-template': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
  'grid-template-rows': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
  'grid-template-columns': {
    values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 },
  },
  'grid-auto-columns': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
  'grid-auto-rows': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
  'text-decoration-style': { prefixes: 1 },
  'text-decoration-color': { prefixes: 1 },
  'text-decoration-line': { prefixes: 1 },
  'text-decoration': { prefixes: 1 },
  'text-decoration-skip': { prefixes: 1 },
  'text-decoration-skip-ink': { prefixes: 1 },
  'text-emphasis': { prefixes: 1 },
  'text-emphasis-position': { prefixes: 1 },
  'text-emphasis-style': { prefixes: 1 },
  'text-emphasis-color': { prefixes: 1 },
  'text-size-adjust': { prefixes: 1 },
  'user-select': { prefixes: 5 },
};

export const selectorMapping: PrefixMap = {
  ':read-only': 2,
  ':read-write': 2,
  ':fullscreen': 5,
  '::backdrop': 5,
};
