/* eslint-disable sort-keys */

import { DeclarationPrefixMap, PrefixMap } from './types';

export const declarationMapping: DeclarationPrefixMap = {
	'background-clip': { prefixes: 5 },
	appearance: { prefixes: 7 },
	'backdrop-filter': { prefixes: 1 },
	'box-decoration-break': { prefixes: 5 },
	'clip-path': { prefixes: 1 },
	'color-adjust': { prefixes: 5 },
	background: { functions: { 'cross-fade': 5, element: 2, 'image-set': 5 } },
	'background-image': { functions: { 'cross-fade': 5, element: 2, 'image-set': 5 } },
	'border-image': { functions: { 'cross-fade': 5, element: 2, 'image-set': 5 } },
	mask: { functions: { 'cross-fade': 5, element: 2, 'image-set': 5 }, prefixes: 5 },
	'list-style': { functions: { 'cross-fade': 5, element: 2, 'image-set': 5 } },
	'list-style-image': { functions: { 'cross-fade': 5, element: 2, 'image-set': 5 } },
	content: { functions: { 'cross-fade': 5, element: 2, 'image-set': 5 } },
	'mask-image': { functions: { 'cross-fade': 5, element: 2, 'image-set': 5 }, prefixes: 5 },
	hyphens: { prefixes: 5 },
	cursor: { functions: { 'image-set': 5 } },
	'mask-border-outset': { prefixes: 5 },
	'mask-border-repeat': { prefixes: 5 },
	'mask-border-slice': { prefixes: 5 },
	'mask-border-source': { prefixes: 5 },
	'mask-border-width': { prefixes: 5 },
	'mask-border': { prefixes: 5 },
	'mask-clip': { prefixes: 5 },
	'mask-composite': { prefixes: 5 },
	'mask-origin': { prefixes: 5 },
	'mask-position': { prefixes: 5 },
	'mask-repeat': { prefixes: 5 },
	'mask-size': { prefixes: 5 },
	'text-orientation': { prefixes: 1 },
	'unicode-bidi': { values: { isolate: 1, 'isolate-override': 1, plaintext: 1 } },
	'tab-size': { prefixes: 2 },
	'font-kerning': { prefixes: 1 },
	width: { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
	'min-width': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
	'max-width': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
	height: { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
	'min-height': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
	'max-height': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
	'inline-size': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
	'min-inline-size': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
	'max-inline-size': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
	'block-size': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
	'min-block-size': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
	'max-block-size': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
	grid: { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
	'grid-template': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
	'grid-template-rows': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
	'grid-template-columns': {
		values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 },
	},
	'grid-auto-columns': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
	'grid-auto-rows': { values: { 'fit-content': 1, fill: 1, 'fill-available': 1, stretch: 1 } },
	'text-decoration-style': { prefixes: 1 },
	'text-decoration-color': { prefixes: 1 },
	'text-decoration-line': { prefixes: 1 },
	'text-decoration': { prefixes: 1 },
	'text-decoration-skip': { prefixes: 1 },
	'text-decoration-skip-ink': { prefixes: 1 },
	'text-emphasis': { prefixes: 5 },
	'text-emphasis-position': { prefixes: 5 },
	'text-emphasis-style': { prefixes: 5 },
	'text-emphasis-color': { prefixes: 5 },
	'text-size-adjust': { prefixes: 5 },
	'user-select': { prefixes: 5 },
};

export const selectorMapping: PrefixMap = {
	':read-only': 2,
	':read-write': 2,
	':fullscreen': 5,
	'::backdrop': 5,
};
