language: node_js
node_js:
  - '8'
  - '10'
  - '12'
matrix:
  fast_finish: true
  allow_failures:
    # Different snapshot output
    - node_js: '12'
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn install --frozen-lockfile --ignore-engines
  # Workspaces only
  - yarn run build
script: yarn test
notifications:
  email: false
cache:
  yarn: true
