language: node_js
node_js:
  - '8'
  - '10'
  - 'node'
matrix:
  fast_finish: true
  allow_failures:
    # Different snapshot output
    - node_js: 'node'
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn install --frozen-lockfile
  # Workspaces only
  - yarn run build
script: yarn test
notifications:
  email: false
cache:
  yarn: true
