// flow-typed signature: a26a2c3961ee0295f8957619e793771a
// flow-typed version: <<STUB>>/babel-plugin-css-modules-transform_v1.3.1/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-css-modules-transform'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-css-modules-transform' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-css-modules-transform/build/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/options_resolvers/append' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/options_resolvers/camelCase' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/options_resolvers/createImportedName' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/options_resolvers/devMode' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/options_resolvers/extensions' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/options_resolvers/generateScopedName' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/options_resolvers/hashPrefix' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/options_resolvers/ignore' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/options_resolvers/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/options_resolvers/mode' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/options_resolvers/prepend' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/options_resolvers/preprocessCss' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/options_resolvers/processCss' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/options_resolvers/processorOpts' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/options_resolvers/rootDir' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/options_resolvers/use' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/utils/extractCssFile' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/utils/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/utils/isBoolean' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/utils/isFunction' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/utils/isModulePath' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/utils/isPlainObject' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/utils/isRegExp' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/utils/isString' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/utils/requireLocalFileOrNodeModule' {
  declare module.exports: any;
}

declare module 'babel-plugin-css-modules-transform/build/utils/writeCssFile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-css-modules-transform/build/index.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/index'>;
}
declare module 'babel-plugin-css-modules-transform/build/options_resolvers/append.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/options_resolvers/append'>;
}
declare module 'babel-plugin-css-modules-transform/build/options_resolvers/camelCase.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/options_resolvers/camelCase'>;
}
declare module 'babel-plugin-css-modules-transform/build/options_resolvers/createImportedName.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/options_resolvers/createImportedName'>;
}
declare module 'babel-plugin-css-modules-transform/build/options_resolvers/devMode.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/options_resolvers/devMode'>;
}
declare module 'babel-plugin-css-modules-transform/build/options_resolvers/extensions.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/options_resolvers/extensions'>;
}
declare module 'babel-plugin-css-modules-transform/build/options_resolvers/generateScopedName.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/options_resolvers/generateScopedName'>;
}
declare module 'babel-plugin-css-modules-transform/build/options_resolvers/hashPrefix.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/options_resolvers/hashPrefix'>;
}
declare module 'babel-plugin-css-modules-transform/build/options_resolvers/ignore.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/options_resolvers/ignore'>;
}
declare module 'babel-plugin-css-modules-transform/build/options_resolvers/index.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/options_resolvers/index'>;
}
declare module 'babel-plugin-css-modules-transform/build/options_resolvers/mode.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/options_resolvers/mode'>;
}
declare module 'babel-plugin-css-modules-transform/build/options_resolvers/prepend.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/options_resolvers/prepend'>;
}
declare module 'babel-plugin-css-modules-transform/build/options_resolvers/preprocessCss.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/options_resolvers/preprocessCss'>;
}
declare module 'babel-plugin-css-modules-transform/build/options_resolvers/processCss.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/options_resolvers/processCss'>;
}
declare module 'babel-plugin-css-modules-transform/build/options_resolvers/processorOpts.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/options_resolvers/processorOpts'>;
}
declare module 'babel-plugin-css-modules-transform/build/options_resolvers/rootDir.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/options_resolvers/rootDir'>;
}
declare module 'babel-plugin-css-modules-transform/build/options_resolvers/use.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/options_resolvers/use'>;
}
declare module 'babel-plugin-css-modules-transform/build/utils/extractCssFile.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/utils/extractCssFile'>;
}
declare module 'babel-plugin-css-modules-transform/build/utils/index.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/utils/index'>;
}
declare module 'babel-plugin-css-modules-transform/build/utils/isBoolean.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/utils/isBoolean'>;
}
declare module 'babel-plugin-css-modules-transform/build/utils/isFunction.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/utils/isFunction'>;
}
declare module 'babel-plugin-css-modules-transform/build/utils/isModulePath.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/utils/isModulePath'>;
}
declare module 'babel-plugin-css-modules-transform/build/utils/isPlainObject.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/utils/isPlainObject'>;
}
declare module 'babel-plugin-css-modules-transform/build/utils/isRegExp.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/utils/isRegExp'>;
}
declare module 'babel-plugin-css-modules-transform/build/utils/isString.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/utils/isString'>;
}
declare module 'babel-plugin-css-modules-transform/build/utils/requireLocalFileOrNodeModule.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/utils/requireLocalFileOrNodeModule'>;
}
declare module 'babel-plugin-css-modules-transform/build/utils/writeCssFile.js' {
  declare module.exports: $Exports<'babel-plugin-css-modules-transform/build/utils/writeCssFile'>;
}
