// flow-typed signature: d80f86b6d7a24339df062c6e89754d38
// flow-typed version: <<STUB>>/fela_v^6.1.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fela'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fela' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fela/es/combineRules' {
  declare module.exports: any;
}

declare module 'fela/es/createRenderer' {
  declare module.exports: any;
}

declare module 'fela/es/cssifyFontFace' {
  declare module.exports: any;
}

declare module 'fela/es/cssifyKeyframe' {
  declare module.exports: any;
}

declare module 'fela/es/cssifyStaticStyle' {
  declare module.exports: any;
}

declare module 'fela/es/enhance' {
  declare module.exports: any;
}

declare module 'fela/es/generateAnimationName' {
  declare module.exports: any;
}

declare module 'fela/es/generateClassName' {
  declare module.exports: any;
}

declare module 'fela/es/generateStaticReference' {
  declare module.exports: any;
}

declare module 'fela/es/getFontFormat' {
  declare module.exports: any;
}

declare module 'fela/es/getFontUrl' {
  declare module.exports: any;
}

declare module 'fela/es/index' {
  declare module.exports: any;
}

declare module 'fela/es/isBase64' {
  declare module.exports: any;
}

declare module 'fela/es/isSafeClassName' {
  declare module.exports: any;
}

declare module 'fela/es/minifyCSSString' {
  declare module.exports: any;
}

declare module 'fela/es/toCSSString' {
  declare module.exports: any;
}

declare module 'fela/lib/combineRules' {
  declare module.exports: any;
}

declare module 'fela/lib/createRenderer' {
  declare module.exports: any;
}

declare module 'fela/lib/cssifyFontFace' {
  declare module.exports: any;
}

declare module 'fela/lib/cssifyKeyframe' {
  declare module.exports: any;
}

declare module 'fela/lib/cssifyStaticStyle' {
  declare module.exports: any;
}

declare module 'fela/lib/enhance' {
  declare module.exports: any;
}

declare module 'fela/lib/generateAnimationName' {
  declare module.exports: any;
}

declare module 'fela/lib/generateClassName' {
  declare module.exports: any;
}

declare module 'fela/lib/generateStaticReference' {
  declare module.exports: any;
}

declare module 'fela/lib/getFontFormat' {
  declare module.exports: any;
}

declare module 'fela/lib/getFontUrl' {
  declare module.exports: any;
}

declare module 'fela/lib/index' {
  declare module.exports: any;
}

declare module 'fela/lib/isBase64' {
  declare module.exports: any;
}

declare module 'fela/lib/isSafeClassName' {
  declare module.exports: any;
}

declare module 'fela/lib/minifyCSSString' {
  declare module.exports: any;
}

declare module 'fela/lib/toCSSString' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fela/es/combineRules.js' {
  declare module.exports: $Exports<'fela/es/combineRules'>;
}
declare module 'fela/es/createRenderer.js' {
  declare module.exports: $Exports<'fela/es/createRenderer'>;
}
declare module 'fela/es/cssifyFontFace.js' {
  declare module.exports: $Exports<'fela/es/cssifyFontFace'>;
}
declare module 'fela/es/cssifyKeyframe.js' {
  declare module.exports: $Exports<'fela/es/cssifyKeyframe'>;
}
declare module 'fela/es/cssifyStaticStyle.js' {
  declare module.exports: $Exports<'fela/es/cssifyStaticStyle'>;
}
declare module 'fela/es/enhance.js' {
  declare module.exports: $Exports<'fela/es/enhance'>;
}
declare module 'fela/es/generateAnimationName.js' {
  declare module.exports: $Exports<'fela/es/generateAnimationName'>;
}
declare module 'fela/es/generateClassName.js' {
  declare module.exports: $Exports<'fela/es/generateClassName'>;
}
declare module 'fela/es/generateStaticReference.js' {
  declare module.exports: $Exports<'fela/es/generateStaticReference'>;
}
declare module 'fela/es/getFontFormat.js' {
  declare module.exports: $Exports<'fela/es/getFontFormat'>;
}
declare module 'fela/es/getFontUrl.js' {
  declare module.exports: $Exports<'fela/es/getFontUrl'>;
}
declare module 'fela/es/index.js' {
  declare module.exports: $Exports<'fela/es/index'>;
}
declare module 'fela/es/isBase64.js' {
  declare module.exports: $Exports<'fela/es/isBase64'>;
}
declare module 'fela/es/isSafeClassName.js' {
  declare module.exports: $Exports<'fela/es/isSafeClassName'>;
}
declare module 'fela/es/minifyCSSString.js' {
  declare module.exports: $Exports<'fela/es/minifyCSSString'>;
}
declare module 'fela/es/toCSSString.js' {
  declare module.exports: $Exports<'fela/es/toCSSString'>;
}
declare module 'fela/lib/combineRules.js' {
  declare module.exports: $Exports<'fela/lib/combineRules'>;
}
declare module 'fela/lib/createRenderer.js' {
  declare module.exports: $Exports<'fela/lib/createRenderer'>;
}
declare module 'fela/lib/cssifyFontFace.js' {
  declare module.exports: $Exports<'fela/lib/cssifyFontFace'>;
}
declare module 'fela/lib/cssifyKeyframe.js' {
  declare module.exports: $Exports<'fela/lib/cssifyKeyframe'>;
}
declare module 'fela/lib/cssifyStaticStyle.js' {
  declare module.exports: $Exports<'fela/lib/cssifyStaticStyle'>;
}
declare module 'fela/lib/enhance.js' {
  declare module.exports: $Exports<'fela/lib/enhance'>;
}
declare module 'fela/lib/generateAnimationName.js' {
  declare module.exports: $Exports<'fela/lib/generateAnimationName'>;
}
declare module 'fela/lib/generateClassName.js' {
  declare module.exports: $Exports<'fela/lib/generateClassName'>;
}
declare module 'fela/lib/generateStaticReference.js' {
  declare module.exports: $Exports<'fela/lib/generateStaticReference'>;
}
declare module 'fela/lib/getFontFormat.js' {
  declare module.exports: $Exports<'fela/lib/getFontFormat'>;
}
declare module 'fela/lib/getFontUrl.js' {
  declare module.exports: $Exports<'fela/lib/getFontUrl'>;
}
declare module 'fela/lib/index.js' {
  declare module.exports: $Exports<'fela/lib/index'>;
}
declare module 'fela/lib/isBase64.js' {
  declare module.exports: $Exports<'fela/lib/isBase64'>;
}
declare module 'fela/lib/isSafeClassName.js' {
  declare module.exports: $Exports<'fela/lib/isSafeClassName'>;
}
declare module 'fela/lib/minifyCSSString.js' {
  declare module.exports: $Exports<'fela/lib/minifyCSSString'>;
}
declare module 'fela/lib/toCSSString.js' {
  declare module.exports: $Exports<'fela/lib/toCSSString'>;
}
