// flow-typed signature: 44a4e17902b20864555b14eb76633e1b
// flow-typed version: <<STUB>>/typestyle_v^1.5.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typestyle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typestyle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typestyle/lib.es2015/index' {
  declare module.exports: any;
}

declare module 'typestyle/lib.es2015/internal/formatting' {
  declare module.exports: any;
}

declare module 'typestyle/lib.es2015/internal/typestyle' {
  declare module.exports: any;
}

declare module 'typestyle/lib.es2015/internal/utilities' {
  declare module.exports: any;
}

declare module 'typestyle/lib.es2015/types' {
  declare module.exports: any;
}

declare module 'typestyle/lib/index' {
  declare module.exports: any;
}

declare module 'typestyle/lib/internal/formatting' {
  declare module.exports: any;
}

declare module 'typestyle/lib/internal/typestyle' {
  declare module.exports: any;
}

declare module 'typestyle/lib/internal/utilities' {
  declare module.exports: any;
}

declare module 'typestyle/lib/types' {
  declare module.exports: any;
}

declare module 'typestyle/umd/typestyle' {
  declare module.exports: any;
}

declare module 'typestyle/umd/typestyle.min' {
  declare module.exports: any;
}

declare module 'typestyle/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typestyle/lib.es2015/index.js' {
  declare module.exports: $Exports<'typestyle/lib.es2015/index'>;
}
declare module 'typestyle/lib.es2015/internal/formatting.js' {
  declare module.exports: $Exports<'typestyle/lib.es2015/internal/formatting'>;
}
declare module 'typestyle/lib.es2015/internal/typestyle.js' {
  declare module.exports: $Exports<'typestyle/lib.es2015/internal/typestyle'>;
}
declare module 'typestyle/lib.es2015/internal/utilities.js' {
  declare module.exports: $Exports<'typestyle/lib.es2015/internal/utilities'>;
}
declare module 'typestyle/lib.es2015/types.js' {
  declare module.exports: $Exports<'typestyle/lib.es2015/types'>;
}
declare module 'typestyle/lib/index.js' {
  declare module.exports: $Exports<'typestyle/lib/index'>;
}
declare module 'typestyle/lib/internal/formatting.js' {
  declare module.exports: $Exports<'typestyle/lib/internal/formatting'>;
}
declare module 'typestyle/lib/internal/typestyle.js' {
  declare module.exports: $Exports<'typestyle/lib/internal/typestyle'>;
}
declare module 'typestyle/lib/internal/utilities.js' {
  declare module.exports: $Exports<'typestyle/lib/internal/utilities'>;
}
declare module 'typestyle/lib/types.js' {
  declare module.exports: $Exports<'typestyle/lib/types'>;
}
declare module 'typestyle/umd/typestyle.js' {
  declare module.exports: $Exports<'typestyle/umd/typestyle'>;
}
declare module 'typestyle/umd/typestyle.min.js' {
  declare module.exports: $Exports<'typestyle/umd/typestyle.min'>;
}
declare module 'typestyle/webpack.config.js' {
  declare module.exports: $Exports<'typestyle/webpack.config'>;
}
