// flow-typed signature: 7cb1258e1fa2434254281e778550fcac
// flow-typed version: <<STUB>>/@milesj/build-tool-config_v^0.43.1/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@milesj/build-tool-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@milesj/build-tool-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@milesj/build-tool-config/babel' {
  declare module.exports: any;
}

declare module '@milesj/build-tool-config/bin/build' {
  declare module.exports: any;
}

declare module '@milesj/build-tool-config/bin/bundle' {
  declare module.exports: any;
}

declare module '@milesj/build-tool-config/bin/check' {
  declare module.exports: any;
}

declare module '@milesj/build-tool-config/bin/init' {
  declare module.exports: any;
}

declare module '@milesj/build-tool-config/bin/lint' {
  declare module.exports: any;
}

declare module '@milesj/build-tool-config/bin/sync' {
  declare module.exports: any;
}

declare module '@milesj/build-tool-config/bin/test' {
  declare module.exports: any;
}

declare module '@milesj/build-tool-config/bin/utils/log' {
  declare module.exports: any;
}

declare module '@milesj/build-tool-config/bin/utils/run' {
  declare module.exports: any;
}

declare module '@milesj/build-tool-config/configs/babel' {
  declare module.exports: any;
}

declare module '@milesj/build-tool-config/configs/eslint' {
  declare module.exports: any;
}

declare module '@milesj/build-tool-config/configs/jest' {
  declare module.exports: any;
}

declare module '@milesj/build-tool-config/configs/webpack' {
  declare module.exports: any;
}

declare module '@milesj/build-tool-config/eslint' {
  declare module.exports: any;
}

declare module '@milesj/build-tool-config/jest-setup' {
  declare module.exports: any;
}

declare module '@milesj/build-tool-config/jest' {
  declare module.exports: any;
}

declare module '@milesj/build-tool-config/webpack' {
  declare module.exports: any;
}

// Filename aliases
declare module '@milesj/build-tool-config/babel.js' {
  declare module.exports: $Exports<'@milesj/build-tool-config/babel'>;
}
declare module '@milesj/build-tool-config/bin/build.js' {
  declare module.exports: $Exports<'@milesj/build-tool-config/bin/build'>;
}
declare module '@milesj/build-tool-config/bin/bundle.js' {
  declare module.exports: $Exports<'@milesj/build-tool-config/bin/bundle'>;
}
declare module '@milesj/build-tool-config/bin/check.js' {
  declare module.exports: $Exports<'@milesj/build-tool-config/bin/check'>;
}
declare module '@milesj/build-tool-config/bin/init.js' {
  declare module.exports: $Exports<'@milesj/build-tool-config/bin/init'>;
}
declare module '@milesj/build-tool-config/bin/lint.js' {
  declare module.exports: $Exports<'@milesj/build-tool-config/bin/lint'>;
}
declare module '@milesj/build-tool-config/bin/sync.js' {
  declare module.exports: $Exports<'@milesj/build-tool-config/bin/sync'>;
}
declare module '@milesj/build-tool-config/bin/test.js' {
  declare module.exports: $Exports<'@milesj/build-tool-config/bin/test'>;
}
declare module '@milesj/build-tool-config/bin/utils/log.js' {
  declare module.exports: $Exports<'@milesj/build-tool-config/bin/utils/log'>;
}
declare module '@milesj/build-tool-config/bin/utils/run.js' {
  declare module.exports: $Exports<'@milesj/build-tool-config/bin/utils/run'>;
}
declare module '@milesj/build-tool-config/configs/babel.js' {
  declare module.exports: $Exports<'@milesj/build-tool-config/configs/babel'>;
}
declare module '@milesj/build-tool-config/configs/eslint.js' {
  declare module.exports: $Exports<'@milesj/build-tool-config/configs/eslint'>;
}
declare module '@milesj/build-tool-config/configs/jest.js' {
  declare module.exports: $Exports<'@milesj/build-tool-config/configs/jest'>;
}
declare module '@milesj/build-tool-config/configs/webpack.js' {
  declare module.exports: $Exports<'@milesj/build-tool-config/configs/webpack'>;
}
declare module '@milesj/build-tool-config/eslint.js' {
  declare module.exports: $Exports<'@milesj/build-tool-config/eslint'>;
}
declare module '@milesj/build-tool-config/jest-setup.js' {
  declare module.exports: $Exports<'@milesj/build-tool-config/jest-setup'>;
}
declare module '@milesj/build-tool-config/jest.js' {
  declare module.exports: $Exports<'@milesj/build-tool-config/jest'>;
}
declare module '@milesj/build-tool-config/webpack.js' {
  declare module.exports: $Exports<'@milesj/build-tool-config/webpack'>;
}
